services:
  - type: web
    name: flask-redirect-checker
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y wget unzip
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt install -y ./google-chrome-stable_current_amd64.deb
      rm google-chrome-stable_current_amd64.deb
      pip install -r requirements.txt
    startCommand: "gunicorn main:app -b 0.0.0.0:$PORT"
